// assets/js/lib/features/configuration/components/global-information-form.svelte
<script lang="ts">
  import { router } from "@inertiajs/svelte";

  import Button from "$lib/components/button.svelte";
  import Field from "$lib/components/field.svelte";
  import Textinput from "$lib/components/textinput.svelte";
  import Form from "$lib/components/form.svelte";
  import type { GlobalMetadata } from "$lib/features/metadata";

  export let initialData: GlobalMetadata["data"];

  let banner: string = initialData.banner;
  let title: string = initialData.title;
  let focusMode: boolean = initialData.focusMode;

  function handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    router.post("/admin", {
      global: {
        banner,
        title,
        focusMode,
      },
    });
  }
</script>

<section class="w-full">
  <h3 class="text-2xl">Global informations</h3>
  <Form on:submit={handleSubmit}>
    <Field label="Banner" htmlFor="banner">
      <Textinput id="banner" bind:value={banner} />
    </Field>

    <Field label="Stream title" htmlFor="title">
      <Textinput id="title" bind:value={title} />
    </Field>

    <Field label="Focus mode" htmlFor="focusMode" inline>
      <input type="checkbox" bind:checked={focusMode} />
    </Field>

    <Button type="submit" fullWidth>Save</Button>
  </Form>
</section>

// assets/js/lib/features/configuration/components/global-information-form.tsx
import { router } from "@inertiajs/react";
import { useState, FormEvent } from "react";

import Button from "../../../components/button";
import Field from "../../../components/field";
import TextInput from "../../../components/textinput";
import Form from "../../../components/form";
import type { GlobalMetadata } from "../../metadata";

interface GlobalInformationFormProps {
  initialData: GlobalMetadata["data"];
}

export default function GlobalInformationForm({ initialData }: GlobalInformationFormProps) {
  const [banner, setBanner] = useState(initialData.banner);
  const [title, setTitle] = useState(initialData.title);
  const [focusMode, setFocusMode] = useState(initialData.focusMode);

  function handleSubmit(event: FormEvent) {
    event.preventDefault();
    router.post("/admin", {
      global: {
        banner,
        title,
        focusMode,
      },
    });
  }

  return (
    <section className="w-full">
      <h3 className="text-2xl">Global informations</h3>
      <Form onSubmit={handleSubmit}>
        <Field label="Banner" htmlFor="banner">
          <TextInput 
            id="banner" 
            value={banner} 
            onChange={(e) => setBanner(e.target.value)} 
          />
        </Field>

        <Field label="Stream title" htmlFor="title">
          <TextInput 
            id="title" 
            value={title} 
            onChange={(e) => setTitle(e.target.value)} 
          />
        </Field>

        <Field label="Focus mode" htmlFor="focusMode" inline>
          <input 
            type="checkbox" 
            checked={focusMode} 
            onChange={(e) => setFocusMode(e.target.checked)} 
          />
        </Field>

        <Button type="submit" fullWidth>Save</Button>
      </Form>
    </section>
  );
}
