// assets/js/lib/components/counter.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";

  export let countdownSeconds: number = 60 * 5;
  let interval: number;

  $: minutes = Math.floor(countdownSeconds / 60);
  $: seconds = countdownSeconds % 60;
  $: formattedSeconds = `${pad(minutes)}:${pad(seconds)}`;
  $: isDone = countdownSeconds <= 0;

  function pad(num: number) {
    return String(num).padStart(2, "0");
  }

  onMount(() => {
    setInterval(() => {
      if (countdownSeconds <= 0) {
        clearInterval(interval);
      }
      countdownSeconds = countdownSeconds - 1;
    }, 1000);
  });

  onDestroy(() => {
    clearInterval(interval);
  });
</script>

{#if isDone}
  <slot />
{:else}
  <div class="w-fit rounded-lg border-4 border-white px-4">
    <p class="text-four tabular-nums text-white">
      {formattedSeconds}
    </p>
  </div>
{/if}

// assets/js/lib/components/counter.tsx
import { useState, useEffect, ReactNode } from "react";

interface CounterProps {
  countdownSeconds: number;
  children?: ReactNode;
}

export default function Counter({ countdownSeconds: initialSeconds, children }: CounterProps) {
  const [countdownSeconds, setCountdownSeconds] = useState(initialSeconds);

  const minutes = Math.floor(countdownSeconds / 60);
  const seconds = countdownSeconds % 60;
  const formattedSeconds = `${pad(minutes)}:${pad(seconds)}`;
  const isDone = countdownSeconds <= 0;

  function pad(num: number) {
    return String(num).padStart(2, "0");
  }

  useEffect(() => {
    const interval = setInterval(() => {
      setCountdownSeconds((prev) => {
        if (prev <= 0) {
          clearInterval(interval);
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  if (isDone) {
    return <>{children}</>;
  }

  return (
    <div className="w-fit rounded-lg border-4 border-white px-4">
      <p className="text-four tabular-nums text-white">
        {formattedSeconds}
      </p>
    </div>
  );
}
