// assets/js/lib/components/integration-status.svelte
<script lang="ts">
  export let isConnected: boolean = false;
</script>

<div
  class:bg-emerald-500={isConnected}
  class:bg-rose-500={!isConnected}
  class="flex w-fit flex-row items-center justify-start rounded-md p-1 text-xs text-white"
>
  {#if isConnected}
    Connected
  {:else}
    Disconnected
  {/if}
</div>

// assets/js/lib/components/integration-status.tsx
interface IntegrationStatusProps {
  isConnected?: boolean;
}

export default function IntegrationStatus({ isConnected = false }: IntegrationStatusProps) {
  return (
    <div
      className={`flex w-fit flex-row items-center justify-start rounded-md p-1 text-xs text-white ${
        isConnected ? "bg-emerald-500" : "bg-rose-500"
      }`}
    >
      {isConnected ? "Connected" : "Disconnected"}
    </div>
  );
}
