// assets/js/lib/components/social-media.svelte
<script lang="ts">
  // @ts-nocheck
  import { TwitterIcon, InstagramIcon } from "lucide-svelte";

  const socialMedia = [
    {
      name: "@LLCoolChris_",
      icon: TwitterIcon,
    },
    {
      name: "@LLCoolChris_",
      icon: InstagramIcon,
    },
  ];
</script>

<div class="flex w-fit flex-row items-center justify-start gap-6">
  {#each socialMedia as socialMedia}
    <div class="flex flex-row items-center justify-start gap-2 text-white">
      <svelte:component this={socialMedia.icon} size={32} />
      <p class="text-six">{socialMedia.name}</p>
    </div>
  {/each}
</div>

// assets/js/lib/components/social-media.tsx
import { Twitter, Instagram } from "lucide-react";

const socialMedia = [
  {
    name: "@LLCoolChris_",
    icon: Twitter,
  },
  {
    name: "@LLCoolChris_",
    icon: Instagram,
  },
];

export default function SocialMedia() {
  return (
    <div className="flex w-fit flex-row items-center justify-start gap-6">
      {socialMedia.map((social, index) => (
        <div key={index} className="flex flex-row items-center justify-start gap-2 text-white">
          <social.icon size={32} />
          <p className="text-six">{social.name}</p>
        </div>
      ))}
    </div>
  );
}
