// assets/js/pages/admin/_layout.svelte
<script lang="ts">
  import { inertia } from "@inertiajs/svelte";
  import Button from "$lib/components/button.svelte";
  import Alert from "$lib/components/alert.svelte";

  export let flash: Record<string, string> = { success: "yes" };

  function onAlertClose() {
    flash = {};
  }
</script>

<nav class="static top-0 w-full">
  <div
    class="relative flex h-16 w-full flex-row items-center justify-between border-b px-4"
  >
    <div>
      <h1>Overlays control panel</h1>
    </div>

    <div class="flex flex-row items-center justify-end gap-4">
      <a use:inertia href="/admin" class="hover:underline">Configuration</a>
      <a use:inertia href="/admin/integrations" class="hover:underline"
        >Integrations</a
      >
      <Button isLink href="/admin/logout">Logout</Button>
    </div>

    {#if Object.keys(flash).length > 0}
      <div
        class="absolute -bottom-0 left-1/2 z-50 -translate-x-1/2 translate-y-[100%] p-4"
      >
        {#if flash.success}
          <Alert
            kind="success"
            message={flash.success}
            on:close={onAlertClose}
          />
        {:else if flash.error}
          <Alert kind="error" message={flash.error} on:close={onAlertClose} />
        {/if}
      </div>
    {/if}
  </div>
</nav>

<slot />

// assets/js/pages/admin/_layout.tsx
import { Link } from "@inertiajs/react";
import { ReactNode } from "react";
import Button from "../../lib/components/button";
import Alert from "../../lib/components/alert";

interface LayoutProps {
  children: ReactNode;
  flash?: Record<string, string>;
}

export default function AdminLayout({ children, flash = {} }: LayoutProps) {
  const handleAlertClose = () => {
    // In React, we would typically manage this through state
    // For now, we'll leave this empty as flash messages are typically
    // handled by the backend/Inertia
  };

  return (
    <>
      <nav className="static top-0 w-full">
        <div className="relative flex h-16 w-full flex-row items-center justify-between border-b px-4">
          <div>
            <h1>Overlays control panel</h1>
          </div>

          <div className="flex flex-row items-center justify-end gap-4">
            <Link href="/admin" className="hover:underline">
              Configuration
            </Link>
            <Link href="/admin/integrations" className="hover:underline">
              Integrations
            </Link>
            <Button isLink href="/admin/logout">
              Logout
            </Button>
          </div>

          {Object.keys(flash).length > 0 && (
            <div className="absolute -bottom-0 left-1/2 z-50 -translate-x-1/2 translate-y-[100%] p-4">
              {flash.success && (
                <Alert
                  kind="success"
                  message={flash.success}
                  onClose={handleAlertClose}
                />
              )}
              {flash.error && (
                <Alert
                  kind="error"
                  message={flash.error}
                  onClose={handleAlertClose}
                />
              )}
            </div>
          )}
        </div>
      </nav>

      {children}
    </>
  );
}
