// assets/js/pages/admin/login.svelte
<script lang="ts">
  import { router } from "@inertiajs/svelte";

  import Field from "$lib/components/field.svelte";
  import Button from "$lib/components/button.svelte";
  import Textinput from "$lib/components/textinput.svelte";
  import Alert from "$lib/components/alert.svelte";

  export let flash: Record<string, string> = {};
  $: error = flash["error"];

  const formValues = {
    username: "",
    password: "",
  };

  function handleSubmit() {
    flash = {};
    router.post("/admin/login", formValues);
  }
</script>

<div class="flex h-full w-full flex-col items-center justify-center gap-4">
  <h1 class="text-2xl">Login</h1>

  {#if error}
    <Alert kind="error" message={error} />
  {/if}

  <form
    on:submit|preventDefault={handleSubmit}
    class="flex w-full max-w-[500px] flex-col gap-4"
  >
    <Field label="Username" htmlFor="username">
      <Textinput id="username" bind:value={formValues.username} />
    </Field>

    <Field label="Password" htmlFor="password">
      <Textinput
        id="password"
        type="password"
        bind:value={formValues.password}
      />
    </Field>

    <Button type="submit" fullWidth>Login</Button>
  </form>
</div>

// assets/js/pages/admin/login.tsx
import { router } from "@inertiajs/react";
import { useState, FormEvent } from "react";

import Field from "../../lib/components/field";
import Button from "../../lib/components/button";
import TextInput from "../../lib/components/textinput";
import Alert from "../../lib/components/alert";

interface LoginProps {
  flash?: Record<string, string>;
}

export default function Login({ flash = {} }: LoginProps) {
  const [formValues, setFormValues] = useState({
    username: "",
    password: "",
  });

  const error = flash["error"];

  function handleSubmit(event: FormEvent) {
    event.preventDefault();
    router.post("/admin/login", formValues);
  }

  return (
    <div className="flex h-full w-full flex-col items-center justify-center gap-4">
      <h1 className="text-2xl">Login</h1>

      {error && <Alert kind="error" message={error} />}

      <form
        onSubmit={handleSubmit}
        className="flex w-full max-w-[500px] flex-col gap-4"
      >
        <Field label="Username" htmlFor="username">
          <TextInput
            id="username"
            value={formValues.username}
            onChange={(e) =>
              setFormValues({ ...formValues, username: e.target.value })
            }
          />
        </Field>

        <Field label="Password" htmlFor="password">
          <TextInput
            id="password"
            type="password"
            value={formValues.password}
            onChange={(e) =>
              setFormValues({ ...formValues, password: e.target.value })
            }
          />
        </Field>

        <Button type="submit" fullWidth>
          Login
        </Button>
      </form>
    </div>
  );
}
